### ISSUE TITLE
release version 0.1.0 is different from the source code

### ISSUE THREAD

**Issue by NIUDEYANG123** [VMadalin/easypermissions-ktx#3]
## Basic Information

Device type: ________
OS version: ________
EasyPermissions version: ________

## Describe the problem

What happened?  What did you expect to happen?

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
 @JvmStatic
    fun somePermissionPermanentlyDenied(
        host: Activity,
        @Size(min = 1) vararg deniedPerms: String
    ): Boolean {
        return PermissionsHelper.newInstance(host).somePermissionPermanentlyDenied(deniedPerms)
    }
```

**Comment by VMadalin** [comment]
Hi @NIUDEYANG123 , thank you for the issue. Seems there was an issue with `bintray` regarding the version. Now this not longer apply since I moved the project to Maven Central on the following PR: https://github.com/VMadalin/easypermissions-ktx/pull/5. In order to have the latest changes use the following:

```gradle
    implementation 'com.vmadalin:easypermissions-ktx:1.0.0'
```
