### ISSUE TITLE
base library error after implementation

### ISSUE THREAD

**Issue by behnawwm** [VMadalin/easypermissions-ktx#7]
After implementing the library, these base Androidx errors appear!
What's the problem?

```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find fragment-1.2.5.aar (androidx.fragment:fragment:1.2.5).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.2.5/fragment-1.2.5.aar
   > Could not find fragment-1.2.5.aar (androidx.fragment:fragment:1.2.5).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.2.5/fragment-1.2.5.aar
   > Could not find fragment-1.2.5.aar (androidx.fragment:fragment:1.2.5).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.2.5/fragment-1.2.5.aar
```

**Comment by VMadalin** [comment]
Hi @behnawwm, First of all thank you for the issue. The problem that you face isn't related with the library and is more with your project. Seems for a reason gradle cannot find properly the fragment dependency. I recommend you check that, probably could be because you don't have present `google()` on repositories. You have more details [here].(https://stackoverflow.com/questions/60221249/could-not-find-fragment-jar-androidx-fragmentfragment1-0-0)

In addition, I recommend you to check the following step by step implementation of the library on the following tutorial: https://www.youtube.com/watch?v=51fX94dU7Og

**Comment by behnawwm** [comment]
Thanks for the quick response!

My problem was all about **proxies**! 
I set a _proper_ proxy and it's working well again.
https://github.com/freedomofdevelopers/fod
